### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by rahulkapoor90** [technophilic/MyVIT-chrome#2]
Just found out about this project. Looks great! but I was wondering if you want to merge this project with us over at https://github.com/rahulkapoor90/VITacademics-Enhancement-Suite. We are a team of 5 members looking to improve the extension and I think myVIT-chrome would help VES users a lot as it has approx. 1440+ users. let me know.

**Comment by technophilic** [comment]
Hey there! Thanks for the invite. But we already have a dedicated team working on MyVIT and we would
like to work on our implementation of the same. We checked out Enhancement Suite, it is a great work!

Cheers, All the best!
